server:
  port: 30022
host: localhost
port: 30022


spring:
  datasource:
    url: jdbc:mysql://148.70.28.112:3306/wowomall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: wowoto
    password: zqhlovekly
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: footPrintService

mybatis:
  mapper-locations: classpath:FootprintMapper/*Mapper.xml
  type-aliases-package: com.xmu.wowomall.footprint.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://148.70.28.112:8761/eureka